- name: "Initial config"
  hosts: all
  become: true
  
  vars:
    - git_repository: "https://github.com/Miner111/Ansible_roles.git"
    - git_branch: "main"
  
  tasks:
    - name: "Tworzenie katalogu ansible roles"
      file:
        path: "/etc/ansible/roles"
        state: directory
        mode: "0755"
    
    - name: "Git"
      git:
        repo: "{{ git_repository }}"
        dest: /etc/ansible/roles
        version: "{{ git_branch }}"